### ISSUE TITLE
Add link to share the app 

### ISSUE THREAD

**Issue by kevinbischof** [kimhogeling/burp2gether#22] opened 2023-07-03 06:59 UTC
When I add the app to my home screen, I can't see the URL anymore. Use the native share option to share the link to all kind of apps would be good.

![Screenshot_2023-07-03-08-58-30-104_android.jpg](https://github.com/kimhogeling/burp2gether/assets/21262141/9ea6aef7-9e9a-4609-8295-3cfff073524f)

**Comment by kimhogeling** [comment] 2023-07-04 07:13
duplicate of #16  ;)

**Closed by kimhogeling** 2023-07-04 07:13 UTC
